export const FETCH_PHONE_START = "FETCH_PHONE_START";
export const FETCH_PHONE_SUCCESS = "FETCH_PHONE_SUCCESS";
export const FETCH_PHONE_FAIL = "FETCH_PHONE_FAIL";

export const LOAD_MORE_PHONES_START = "LOAD_MORE_PHONES_START";
export const LOAD_MORE_PHONES_SUCCESS = "LOAD_MORE_PHONES_SUCCESS";
export const LOAD_MORE_PHONES_FAIL = "LOAD_MORE_PHONES_FAIL";

export const FETCH_PHONE_BY_ID_START = "FETCH_PHONE_BY_ID_START";
export const FETCH_PHONE_BY_ID_SUCCESS = "FETCH_PHONE_BY_ID_SUCCSESS";
export const FETCH_PHONE_BY_ID_FAIL = "FETCH_PHONE_BY_ID_FAIL";

export const ADD_PHONE_TO_BASKET = "ADD_PHONE_TO_BASKET";

export const SEARCH_PHONE = "SEARCH_PHONE";

export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const SHOW_CATEGORIES_START = "SHOW_CATEGORIES_START";
export const SHOW_CATEGORIES_SUCCESS = "SHOW_CATEGORIES_SUCCESS";
export const SHOW_CATEGORIES_FAIL = "SHOW_CATEGORIES_FAIL";

export const GET_CATEGORY_BY_ID_START = "GET_CATEGORY_BY_ID_START";
export const GET_CATEGORY_BY_ID_SUCCESS = "GET_CATEGORY_BY_ID_SUCCESS";
export const GET_CATEGORY_BY_ID_FAIL = "GET_CATEGORY_BY_ID_FAIL";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
