export const FETCH_PHONE_START = 'FETCH_PHONE_START';
export const FETCH_PHONE_SUCCESS = 'FETCH_PHONE_SUCCESS';
export const FETCH_PHONE_FAIL = 'FETCH_PHONE_FAIL';

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS';
export const LOAD_MORE_PHONES_FAIL = 'LOAD_MORE_PHONES_FAIL';

export const FETCH_PHONE_BY_ID_START = 'FETCH_PHONE_BY_ID_START';
export const FETCH_PHONE_BY_ID_SUCCESS = 'FETCH_PHONE_BY_ID_SUCCSESS';
export const FETCH_PHONE_BY_ID_FAIL = 'FETCH_PHONE_BY_ID_FAIL';
